spring.application.name=notes-service

spring.data.mongodb.uri=mongodb://localhost:27017/notesdb

patient.service.url=http://patient-service:8081/api/patients

#spring.data.mongodb.uri=mongodb://mongodb:27017/notesdb


patient.service.user=admin
patient.service.password=1234


server.port=8083

