spring.application.name=risque-assessment-service

patient.service.url=http://patient-service:8081/api/patients
notes.service.url=http://notes-service:8083/api/notes
server.port=8084

patient.service.user=admin
patient.service.password=1234