spring.application.name=front-service


risk.service.url=http://risk-assessment-service:8084/api/risk
notes.service.url=http://notes-service:8083

server.port=8082

#notes.service.user=admin
#notes.service.password=1234

spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=20
