spring.application.name=patient-service

# Configuration de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/patientdb

# Port d'ecoute du microservice back
server.port=8081

# Config Resource Server (clé secrète)
spring.security.oauth2.resourceserver.jwt.secret-value=MySuperSecretKeyHere
