server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-value: MyJwtSecret12345  # Même secret que patient-service

cloud:
  gateway:
    routes:
      - id: patient-service
        uri: http://patient-service:8081
        predicates:
          - Path=/api/patients/**
      - id: notes-service
        uri: http://notes-service:8083
        predicates:
          - Path=/api/notes/**
      - id: risk-service
        uri: http://risk-assessment-service:8084
        predicates:
          - Path=/api/risk/**

